# Generated by Django 6.0.6 on 2026-06-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('operating_system', models.CharField(max_length=100)),
                ('cpu_usage', models.IntegerField()),
                ('ram_usage', models.IntegerField()),
                ('disk_usage', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
